### ISSUE TITLE
File sizes don't display correct values.

### ISSUE THREAD

**Issue by iterma** [kxxt/WSLDiskShrinker#5]
Not essential, but some file sizes don't display correct values, f.ex.:

| value         | shows       | instead of   |       |
| -------------:| -----------:| -----------:| ----- |
| 1 023         | 1 KiB       | 1023 B      | 🙁   |
| 1 048 571     | 1024 KiB    | 1 MiB       | 🙁🙁 |
| 16 887 317    | 16,1 MiB    | 16,11 MiB   | 😉   |
| 16 960 717    | 16,17 MiB   | 16,18 MiB   | 😉   |
| 16 981 689    | 16,19 MiB   | 16,2 MiB    | 😉   |
| 1 073 736 582 | 1023,99 MiB | 1 GiB       | 🙁   |

**Comment by kxxt** [comment]
Implemented in #7 and included in v0.2.2
